-- script teste pra popular o banco de dados
DROP TABLE IF EXISTS tbEcoponto;
CREATE TABLE tbEcoponto (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_local VARCHAR NOT NULL,
    endereco VARCHAR NOT NULL,
    imagem_url VARCHAR,
    cidade VARCHAR NOT NULL,
    estado VARCHAR(2) NOT NULL,
    telefone VARCHAR(9),
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    hora_aberto TIME,
    hora_fechado TIME,
    aceita_entulho BOOLEAN NOT NULL DEFAULT 0,
    aceita_construcao BOOLEAN NOT NULL DEFAULT 0,
    aceita_papel BOOLEAN NOT NULL DEFAULT 0,
    aceita_papelao BOOLEAN NOT NULL DEFAULT 0,
    aceita_vidro BOOLEAN NOT NULL DEFAULT 0,
    aceita_metal BOOLEAN NOT NULL DEFAULT 0,
    aceita_movel BOOLEAN NOT NULL DEFAULT 0,
    aceita_poda_arvore BOOLEAN NOT NULL DEFAULT 0,
    aceita_bateria BOOLEAN NOT NULL DEFAULT 0,
    aceita_monitor BOOLEAN NOT NULL DEFAULT 0,
    aceita_celular BOOLEAN NOT NULL DEFAULT 0,
    aceita_impressora BOOLEAN NOT NULL DEFAULT 0
);
INSERT INTO tbEcoponto (
        nome_local,
        endereco,
        cidade,
        estado,
        telefone,
        latitude,
        longitude,
        hora_aberto,
        hora_fechado,
        aceita_entulho,
        aceita_construcao,
        aceita_papel,
        aceita_papelao,
        aceita_vidro,
        aceita_metal,
        aceita_movel,
        aceita_poda_arvore,
        aceita_bateria,
        aceita_monitor,
        aceita_celular,
        aceita_impressora
    )
VALUES (
        'Ecoponto Vila Madalena',
        'R. Girassol, 123',
        'São Paulo',
        'SP',
        '1134567890',
        -23.5505,
        -46.6333,
        '08:00:00',
        '18:00:00',
        1,
        1,
        1,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0
    ),
    (
        'Ecoponto Ipanema',
        'Av. Vieira Souto, 456',
        'Rio de Janeiro',
        'RJ',
        '2134567890',
        -22.9836,
        -43.1865,
        '07:00:00',
        '17:00:00',
        0,
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ),
    (
        'Ecoponto Belo Horizonte',
        'R. da Bahia, 789',
        'Belo Horizonte',
        'MG',
        '3134567890',
        -19.9167,
        -43.9333,
        '09:00:00',
        '19:00:00',
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    );